list(APPEND cmeps_src_files

    ../CMEPS/nems/util/shr_abort_mod.F90
    ../CMEPS/nems/util/shr_log_mod.F90
    ../CMEPS/nems/util/shr_pio_mod.F90
    ../CMEPS/nems/util/shr_sys_mod.F90
    ../CMEPS/nems/util/shr_flux_mod.F90
    ../CMEPS/nems/util/shr_mpi_mod.F90
    ../CMEPS/nems/util/glc_elevclass_mod.F90
    ../CMEPS/nems/util/shr_mem_mod.F90
    ../CMEPS/nems/util/shr_kind_mod.F90
    ../CMEPS/nems/util/perf_mod.F90
    ../CMEPS/nems/util/shr_const_mod.F90

    ../CMEPS/mediator/med_phases_restart_mod.F90
    ../CMEPS/mediator/med_map_mod.F90
    ../CMEPS/mediator/med_methods_mod.F90
    ../CMEPS/mediator/med_phases_prep_ice_mod.F90
    ../CMEPS/mediator/med_phases_history_mod.F90
    ../CMEPS/mediator/med_phases_prep_glc_mod.F90
    ../CMEPS/mediator/med_internalstate_mod.F90
    ../CMEPS/mediator/med_phases_profile_mod.F90
    ../CMEPS/mediator/esmFldsExchange_hafs_mod.F90
    ../CMEPS/mediator/med_phases_prep_rof_mod.F90
    ../CMEPS/mediator/esmFldsExchange_cesm_mod.F90
    ../CMEPS/mediator/med_merge_mod.F90
    ../CMEPS/mediator/med_constants_mod.F90
    ../CMEPS/mediator/med_kind_mod.F90
    ../CMEPS/mediator/esmFldsExchange_nems_mod.F90
    ../CMEPS/mediator/med_phases_prep_lnd_mod.F90
    ../CMEPS/mediator/med_phases_prep_atm_mod.F90
    ../CMEPS/mediator/med_phases_prep_ocn_mod.F90
    ../CMEPS/mediator/esmFlds.F90
    ../CMEPS/mediator/med.F90
    ../CMEPS/mediator/med_time_mod.F90
    ../CMEPS/mediator/med_phases_ocnalb_mod.F90
    ../CMEPS/mediator/med_phases_prep_wav_mod.F90
    ../CMEPS/mediator/med_utils_mod.F90
    ../CMEPS/mediator/med_fraction_mod.F90
    ../CMEPS/mediator/med_phases_aofluxes_mod.F90
    ../CMEPS/mediator/med_io_mod.F90
)
